ДЗ Урок 2
meat08/geekbrains pull request #10
Opened 2020-02-24 21:28 UTC by meat08

2020-02-25 21:32 UTC, OKrylov requested changes
В целом все отлично, но есть пара мелких замечаний

2020-02-25 21:32 UTC, OKrylov commented on src/ru/geekbrains/java2/lessontwo/MyArrayDataException.java
> +    private int sum;
поле нигде не используется

2020-02-25 21:32 UTC, OKrylov commented on src/ru/geekbrains/java2/lessontwo/TestExceptions.java
> +        if (arr.length > 4 | arr[0].length > 4) throw new MyArraySizeException();
что если вторая, третья или четвертая строка будут размеров != 4?

2020-02-25 21:32 UTC, OKrylov commented on src/ru/geekbrains/java2/lessontwo/TestExceptions.java
> +    public static boolean isInteger(String s) {
метод называется "этоЕстьЧисло", но по факту проверяет, что строка не является числом

2020-02-25 21:49 UTC, meat08 commented on src/ru/geekbrains/java2/lessontwo/MyArrayDataException.java
> +    private int sum;
Поправил. Добавлял поле sum, чтобы выводить сумму элементов до появления ошибки, но потом отказался от этой идеи, а поле забыл убрать.

2020-02-25 21:50 UTC, meat08 commented on src/ru/geekbrains/java2/lessontwo/TestExceptions.java
> +        if (arr.length > 4 | arr[0].length > 4) throw new MyArraySizeException();
Поправил.

2020-02-25 21:51 UTC, meat08 commented on src/ru/geekbrains/java2/lessontwo/TestExceptions.java
> +    public static boolean isInteger(String s) {
Поправил. Несколько раз исправлял туда-сюда и в итоге сам себя запутал.

2020-03-03 09:14 UTC, okrylov-axcient approved these changes
В целом по ДЗ все отлично, но советую обратить внимание на замечания

2020-03-03 09:14 UTC, okrylov-axcient commented on src/ru/geekbrains/java2/lessontwo/MyArrayDataException.java
> +        this.x = x;
проще добавить `super("Ошибка преобразования. В ячейке [" + x + "][" + y + "] не число.")`, чем переопределять метод и добавлять поля

2020-03-03 09:14 UTC, okrylov-axcient commented on src/ru/geekbrains/java2/lessontwo/MyArraySizeException.java
> +        return "Ошибка размера массива. Максимальный размер 4.";
аналогично замечанию выше

2020-03-03 09:14 UTC, okrylov-axcient commented on src/ru/geekbrains/java2/lessontwo/TestExceptions.java
> +        if (arr.length > 4) throw new MyArraySizeException();
лучше заменить на строгое неравенство `arr.length != 4`

2020-03-03 09:14 UTC, okrylov-axcient commented on src/ru/geekbrains/java2/lessontwo/TestExceptions.java
> +            if(arr[i].length > 4) throw new MyArraySizeException();
лучше заменить на строгое неравенство `arr[i].length != 4`

2020-03-03 09:54 UTC, meat08 commented on src/ru/geekbrains/java2/lessontwo/MyArrayDataException.java
> +        this.x = x;
Действительно. Пофиксил.

2020-03-03 09:54 UTC, meat08 commented on src/ru/geekbrains/java2/lessontwo/MyArraySizeException.java
> +        return "Ошибка размера массива. Максимальный размер 4.";
Fix

2020-03-03 09:56 UTC, merged